import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from "react"
import { Inter } from 'next/font/google'
import { AwesomeButton } from "react-awesome-button"
import AwesomeButtonStyles from 'react-awesome-button/src/styles/styles.scss';

import ConnectWalletButton from '@/components/ConnectWalletButton'
import HomeComponent from '@/components/HomeComponent'

import { get_all_hourly_price_data, get_current_six_hour_event_data } from '@/utils/api_calls/over_under_api_calls'

const inter = Inter({ subsets: ['latin'] })


const Home = ({ server_data }) => {
  const btc_data = server_data['btc'];
  const eth_data = server_data['eth'];
  const contract_data = server_data['events'];
  const provider_url = server_data['provider_url'];



  return (
    <>
      <Head>
        <title>Over-Under-Betting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home-container">
        <div className="navbar">
          <div className="nav-link"> <AwesomeButton> BROWSE MARKETS </AwesomeButton> </div>
          <div className="nav-link"> <AwesomeButton> DOCS </AwesomeButton> </div>
          <div className="nav-link"> <AwesomeButton> ADDITIONAL INFO </AwesomeButton> </div>
          <div className="connect-wallet-btn"> <ConnectWalletButton /> </div>
        </div>

        <div className="carousel-component-container"> <HomeComponent server_data={server_data} /> </div>

        <div className="social-navbar"> SOCIAL LINKS </div>
      </div>
    </>
  )
}

// For now just get data for charts
export const getServerSideProps = async () => {
  const price_data = await get_all_hourly_price_data(24);
  const contract_data = await get_current_six_hour_event_data();
  const provider_url = process.env.NEXT_SEPOLIA_URL;

  const server_data = {
    btc: price_data.btc,
    eth: price_data.eth,
    events: contract_data,
    provider_url: provider_url
  }

  return {
    props: { server_data }
  };
};

export default Home;
